/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'business-details': BusinessDetail;
    'ad-campaigns': AdCampaign;
    'payment-budgeting': PaymentBudgeting;
    'subscription-plans': SubscriptionPlan;
    'user-documents': UserDocument;
    'user-bank-details': UserBankDetail;
    'user-training': UserTraining;
    'user-onboarding': UserOnboarding;
    'driver-earnings': DriverEarning;
    'driver-withdrawals': DriverWithdrawal;
    'driver-ratings': DriverRating;
    'driver-notifications': DriverNotification;
    'driver-magazines': DriverMagazine;
    'driver-magazine-reads': DriverMagazineRead;
    'campaign-performance': CampaignPerformance;
    'campaign-media': CampaignMedia;
    invoices: Invoice;
    'analytics-data': AnalyticsDatum;
    'profile-pictures': ProfilePicture;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'business-details': BusinessDetailsSelect<false> | BusinessDetailsSelect<true>;
    'ad-campaigns': AdCampaignsSelect<false> | AdCampaignsSelect<true>;
    'payment-budgeting': PaymentBudgetingSelect<false> | PaymentBudgetingSelect<true>;
    'subscription-plans': SubscriptionPlansSelect<false> | SubscriptionPlansSelect<true>;
    'user-documents': UserDocumentsSelect<false> | UserDocumentsSelect<true>;
    'user-bank-details': UserBankDetailsSelect<false> | UserBankDetailsSelect<true>;
    'user-training': UserTrainingSelect<false> | UserTrainingSelect<true>;
    'user-onboarding': UserOnboardingSelect<false> | UserOnboardingSelect<true>;
    'driver-earnings': DriverEarningsSelect<false> | DriverEarningsSelect<true>;
    'driver-withdrawals': DriverWithdrawalsSelect<false> | DriverWithdrawalsSelect<true>;
    'driver-ratings': DriverRatingsSelect<false> | DriverRatingsSelect<true>;
    'driver-notifications': DriverNotificationsSelect<false> | DriverNotificationsSelect<true>;
    'driver-magazines': DriverMagazinesSelect<false> | DriverMagazinesSelect<true>;
    'driver-magazine-reads': DriverMagazineReadsSelect<false> | DriverMagazineReadsSelect<true>;
    'campaign-performance': CampaignPerformanceSelect<false> | CampaignPerformanceSelect<true>;
    'campaign-media': CampaignMediaSelect<false> | CampaignMediaSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'analytics-data': AnalyticsDataSelect<false> | AnalyticsDataSelect<true>;
    'profile-pictures': ProfilePicturesSelect<false> | ProfilePicturesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  role: 'admin' | 'user';
  emailVerified?: boolean | null;
  otp?: string | null;
  otpExpiry?: string | null;
  passwordResetToken?: string | null;
  passwordResetExpiry?: string | null;
  passwordChangedAt?: string | null;
  /**
   * Collected during onboarding
   */
  firstName?: string | null;
  /**
   * Collected during onboarding
   */
  lastName?: string | null;
  /**
   * Contact number collected during onboarding
   */
  phoneNumber?: string | null;
  /**
   * Home address collected during onboarding
   */
  address?: string | null;
  /**
   * who referred user
   */
  references?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-details".
 */
export interface BusinessDetail {
  id: string;
  companyEmail: string;
  password: string;
  companyName: string;
  companyAddress: string;
  contact: string;
  industry: string;
  emailVerified?: boolean | null;
  verificationCode?: string | null;
  registrationStatus?: ('pending' | 'email_verified' | 'campaign_setup' | 'payment_setup' | 'completed') | null;
  registrationDate?: string | null;
  lastLogin?: string | null;
  lastLogout?: string | null;
  passwordResetToken?: string | null;
  passwordResetExpiry?: string | null;
  passwordChangedAt?: string | null;
  verificationCodeExpiry?: string | null;
  /**
   * URL to the business profile picture
   */
  profilePicture?: string | null;
  /**
   * When the profile picture was last updated
   */
  profilePictureUpdatedAt?: string | null;
  /**
   * Reference to the ProfilePictures collection
   */
  profilePictureId?: (string | null) | ProfilePicture;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-pictures".
 */
export interface ProfilePicture {
  id: string;
  /**
   * Alt text for the profile picture
   */
  alt: string;
  /**
   * Optional caption for the profile picture
   */
  caption?: string | null;
  /**
   * Type of profile picture owner
   */
  ownerType: 'user' | 'business';
  /**
   * ID of the user or business that owns this profile picture
   */
  ownerId: string;
  /**
   * Whether this is the active profile picture
   */
  isActive?: boolean | null;
  /**
   * User who uploaded this profile picture
   */
  uploadedBy?: (string | null) | User;
  /**
   * File size in bytes
   */
  fileSize?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  /**
   * MIME type of the uploaded file
   */
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-campaigns".
 */
export interface AdCampaign {
  id: string;
  businessId: string | BusinessDetail;
  campaignName: string;
  campaignDescription?: string | null;
  campaignType: 'magazine' | 'digital' | 'qr_engagement';
  budget: number;
  budgetSpent?: number | null;
  startDate: string;
  endDate: string;
  targetAudience?: string | null;
  status?:
    | ('draft' | 'pending_review' | 'approved' | 'active' | 'paused' | 'completed' | 'cancelled' | 'rejected')
    | null;
  approvalStatus?: ('pending' | 'under_review' | 'approved' | 'rejected') | null;
  reviewedBy?: (string | null) | User;
  reviewedAt?: string | null;
  rejectionReason?: string | null;
  notes?: string | null;
  pausedAt?: string | null;
  pauseReason?: string | null;
  resumedAt?: string | null;
  resumeReason?: string | null;
  cancelledAt?: string | null;
  cancelReason?: string | null;
  refundAmount?: number | null;
  lastStatusChange?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-budgeting".
 */
export interface PaymentBudgeting {
  id: string;
  businessId: string | BusinessDetail;
  campaignId: string | AdCampaign;
  amount: number;
  currency?: string | null;
  paymentMethod?: ('card' | 'bank_transfer' | 'ussd' | 'qr_code') | null;
  customerEmail: string;
  customerName?: string | null;
  description?: string | null;
  paymentReference: string;
  paystackReference?: string | null;
  status?: ('pending' | 'successful' | 'failed' | 'cancelled') | null;
  paidAt?: string | null;
  paystackResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  selectedPlan?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-plans".
 */
export interface SubscriptionPlan {
  id: string;
  planName: string;
  planType: 'Essentials Plan' | 'Growth Plan' | 'Impact Plan';
  /**
   * Price in your currency (e.g., NGN)
   */
  price: number;
  currency?: string | null;
  billingCycle?: ('monthly' | 'yearly') | null;
  /**
   * Plan description
   */
  description?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-documents".
 */
export interface UserDocument {
  id: string;
  userId: string | User;
  documentType: 'drivers_license' | 'national_id' | 'vehicle_registration';
  documentFile: string | Media;
  verificationStatus?: ('pending' | 'approved' | 'rejected') | null;
  rejectionReason?: string | null;
  uploadedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-bank-details".
 */
export interface UserBankDetail {
  id: string;
  userId: string | User;
  bankName:
    | 'access_bank'
    | 'fidelity_bank'
    | 'fcmb'
    | 'first_bank'
    | 'gtbank'
    | 'uba'
    | 'zenith_bank'
    | 'citibank'
    | 'ecobank'
    | 'heritage_bank'
    | 'globus_bank'
    | 'keystone_bank'
    | 'polaris_bank'
    | 'stanbic_ibtc'
    | 'standard_chartered'
    | 'sterling_bank'
    | 'titan_trust_bank'
    | 'union_bank'
    | 'unity_bank'
    | 'wema_bank'
    | 'premium_trust_bank'
    | 'optimus_bank'
    | 'providus_bank'
    | 'parallex_bank'
    | 'kuda_bank'
    | 'opay'
    | 'moniepoint'
    | 'palmpay'
    | 'fairmoney'
    | 'vfd_bank'
    | 'nombank'
    | 'aaa_finance';
  accountName: string;
  /**
   * Must be exactly 10 digits
   */
  accountNumber: string;
  verificationStatus?: ('pending' | 'verified' | 'failed') | null;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-training".
 */
export interface UserTraining {
  id: string;
  userId: string | User;
  trainingVideos?:
    | {
        videoId: string;
        videoTitle: string;
        completed?: boolean | null;
        completedAt?: string | null;
        /**
         * Watch time in seconds
         */
        watchTime?: number | null;
        id?: string | null;
      }[]
    | null;
  termsAccepted?: boolean | null;
  termsAcceptedAt?: string | null;
  trainingCompleted?: boolean | null;
  trainingCompletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-onboarding".
 */
export interface UserOnboarding {
  id: string;
  userId: string | User;
  currentStep?: ('basic_details' | 'document_upload' | 'bank_payment' | 'training' | 'completed') | null;
  stepsCompleted?:
    | {
        step?: ('basic_details' | 'document_upload' | 'bank_payment' | 'training' | 'completed') | null;
        completedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  onboardingStatus?: ('in_progress' | 'pending_review' | 'approved' | 'rejected' | 'completed') | null;
  startedAt?: string | null;
  completedAt?: string | null;
  approvedAt?: string | null;
  /**
   * Internal notes for admin review
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-earnings".
 */
export interface DriverEarning {
  id: string;
  /**
   * Driver who earned this amount
   */
  driver: string | User;
  /**
   * Number of scans completed
   */
  scans: number;
  /**
   * Points earned (1 scan = 1 point)
   */
  points: number;
  /**
   * Earnings amount (points × 500 Naira)
   */
  amount: number;
  currency: 'USD' | 'EUR' | 'GBP' | 'NGN';
  type: 'scan_payment' | 'trip_payment' | 'bonus' | 'referral' | 'incentive' | 'other';
  status: 'pending' | 'paid' | 'failed' | 'cancelled';
  /**
   * Description of the earnings
   */
  description?: string | null;
  /**
   * Trip ID if applicable
   */
  tripId?: string | null;
  /**
   * Date when payment was made
   */
  paidAt?: string | null;
  /**
   * Payment method used
   */
  paymentMethod?: ('bank_transfer' | 'mobile_money' | 'cash' | 'other') | null;
  /**
   * Transaction reference ID
   */
  transactionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-withdrawals".
 */
export interface DriverWithdrawal {
  id: string;
  /**
   * Driver requesting withdrawal
   */
  driver: string | User;
  /**
   * Withdrawal amount in Naira
   */
  amount: number;
  currency: 'NGN';
  status: 'pending' | 'approved' | 'rejected' | 'processing' | 'completed';
  bankDetails: {
    bankName: string;
    accountName: string;
    accountNumber: string;
  };
  /**
   * Reason for withdrawal (optional)
   */
  reason?: string | null;
  /**
   * Admin notes (only visible to admins)
   */
  adminNotes?: string | null;
  /**
   * Date when withdrawal was processed
   */
  processedAt?: string | null;
  /**
   * Admin who processed the withdrawal
   */
  processedBy?: (string | null) | User;
  /**
   * Transaction reference ID
   */
  transactionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-ratings".
 */
export interface DriverRating {
  id: string;
  /**
   * Driver being rated
   */
  driver: string | User;
  /**
   * User who gave the rating
   */
  rater: string | User;
  /**
   * Rating from 1 to 5 stars
   */
  rating: number;
  /**
   * Written review/feedback
   */
  review?: string | null;
  /**
   * Trip ID if applicable
   */
  tripId?: string | null;
  category: 'overall' | 'punctuality' | 'vehicle' | 'communication' | 'safety' | 'friendliness';
  /**
   * Whether this rating is verified
   */
  isVerified?: boolean | null;
  /**
   * Whether this rating is public
   */
  isPublic?: boolean | null;
  /**
   * Driver response to the rating
   */
  response?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-notifications".
 */
export interface DriverNotification {
  id: string;
  /**
   * Driver who will receive this notification
   */
  driver: string | User;
  type: 'earnings' | 'rating' | 'trip' | 'system' | 'payment' | 'document' | 'training' | 'general';
  /**
   * Notification title
   */
  title: string;
  /**
   * Notification message content
   */
  message: string;
  /**
   * Whether the notification has been read
   */
  isRead?: boolean | null;
  /**
   * URL to navigate to when notification is clicked
   */
  actionUrl?: string | null;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  /**
   * When this notification expires
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-magazines".
 */
export interface DriverMagazine {
  id: string;
  /**
   * Magazine title
   */
  title: string;
  /**
   * Magazine description
   */
  description?: string | null;
  /**
   * Magazine content
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Magazine cover image URL
   */
  imageUrl?: string | null;
  /**
   * Estimated read time in minutes
   */
  readTime?: number | null;
  category: 'news' | 'tips' | 'safety' | 'earnings' | 'community' | 'updates';
  /**
   * Whether this magazine is published
   */
  isPublished?: boolean | null;
  /**
   * When this magazine was published
   */
  publishedAt?: string | null;
  /**
   * Tags for categorization
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-magazine-reads".
 */
export interface DriverMagazineRead {
  id: string;
  /**
   * Driver who read the magazine
   */
  driver: string | User;
  /**
   * Magazine that was read
   */
  magazine: string | DriverMagazine;
  /**
   * Whether the magazine has been read
   */
  isRead?: boolean | null;
  /**
   * When the magazine was read
   */
  readAt?: string | null;
  /**
   * Reading progress percentage (0-100)
   */
  readProgress?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-performance".
 */
export interface CampaignPerformance {
  id: string;
  campaignId: string | AdCampaign;
  businessId: string | BusinessDetail;
  date: string;
  impressions?: number | null;
  clicks?: number | null;
  conversions?: number | null;
  spend?: number | null;
  engagementRate?: number | null;
  clickThroughRate?: number | null;
  conversionRate?: number | null;
  costPerClick?: number | null;
  costPerConversion?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-media".
 */
export interface CampaignMedia {
  id: string;
  campaignId: string | AdCampaign;
  businessId: string | BusinessDetail;
  fileName: string;
  fileType: 'pdf' | 'jpeg' | 'png' | 'gif' | 'mp4' | 'other';
  fileUrl: string;
  fileSize: number;
  description?: string | null;
  uploadStatus?: ('uploading' | 'completed' | 'failed') | null;
  isApproved?: boolean | null;
  approvedBy?: (string | null) | User;
  approvedAt?: string | null;
  rejectionReason?: string | null;
  uploadedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  invoiceNumber: string;
  businessId: string | BusinessDetail;
  campaignId: string | AdCampaign;
  stripePaymentIntentId: string;
  stripeSessionId?: string | null;
  amount: number;
  currency: 'NGN' | 'USD' | 'EUR';
  status: 'draft' | 'pending_payment' | 'paid' | 'failed' | 'refunded' | 'cancelled';
  paymentStatus?: ('pending' | 'processing' | 'succeeded' | 'failed' | 'cancelled') | null;
  dueDate: string;
  paidAt?: string | null;
  items?:
    | {
        description: string;
        quantity: number;
        unitPrice: number;
        total: number;
        id?: string | null;
      }[]
    | null;
  subtotal: number;
  taxRate?: number | null;
  taxAmount?: number | null;
  totalAmount: number;
  notes?: string | null;
  paymentMethod?: ('stripe' | 'bank_transfer' | 'cash') | null;
  refundReason?: string | null;
  refundedAt?: string | null;
  refundAmount?: number | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-data".
 */
export interface AnalyticsDatum {
  id: string;
  campaignId: string | AdCampaign;
  businessId: string | BusinessDetail;
  date: string;
  impressions?: number | null;
  clicks?: number | null;
  conversions?: number | null;
  spend?: number | null;
  engagementRate?: number | null;
  clickThroughRate?: number | null;
  conversionRate?: number | null;
  costPerClick?: number | null;
  costPerConversion?: number | null;
  costPerMille?: number | null;
  currency: 'NGN' | 'USD' | 'EUR';
  source?: ('magazine' | 'digital' | 'qr_code' | 'social_media' | 'email') | null;
  deviceType?: ('desktop' | 'mobile' | 'tablet' | 'all') | null;
  /**
   * Geographic location (e.g., Lagos, Abuja)
   */
  location?: string | null;
  ageGroup?: ('18-24' | '25-34' | '35-44' | '45-54' | '55+' | 'all') | null;
  gender?: ('male' | 'female' | 'other' | 'all') | null;
  isActive?: boolean | null;
  /**
   * Additional notes or comments about this analytics data
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'business-details';
        value: string | BusinessDetail;
      } | null)
    | ({
        relationTo: 'ad-campaigns';
        value: string | AdCampaign;
      } | null)
    | ({
        relationTo: 'payment-budgeting';
        value: string | PaymentBudgeting;
      } | null)
    | ({
        relationTo: 'subscription-plans';
        value: string | SubscriptionPlan;
      } | null)
    | ({
        relationTo: 'user-documents';
        value: string | UserDocument;
      } | null)
    | ({
        relationTo: 'user-bank-details';
        value: string | UserBankDetail;
      } | null)
    | ({
        relationTo: 'user-training';
        value: string | UserTraining;
      } | null)
    | ({
        relationTo: 'user-onboarding';
        value: string | UserOnboarding;
      } | null)
    | ({
        relationTo: 'driver-earnings';
        value: string | DriverEarning;
      } | null)
    | ({
        relationTo: 'driver-withdrawals';
        value: string | DriverWithdrawal;
      } | null)
    | ({
        relationTo: 'driver-ratings';
        value: string | DriverRating;
      } | null)
    | ({
        relationTo: 'driver-notifications';
        value: string | DriverNotification;
      } | null)
    | ({
        relationTo: 'driver-magazines';
        value: string | DriverMagazine;
      } | null)
    | ({
        relationTo: 'driver-magazine-reads';
        value: string | DriverMagazineRead;
      } | null)
    | ({
        relationTo: 'campaign-performance';
        value: string | CampaignPerformance;
      } | null)
    | ({
        relationTo: 'campaign-media';
        value: string | CampaignMedia;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'analytics-data';
        value: string | AnalyticsDatum;
      } | null)
    | ({
        relationTo: 'profile-pictures';
        value: string | ProfilePicture;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  role?: T;
  emailVerified?: T;
  otp?: T;
  otpExpiry?: T;
  passwordResetToken?: T;
  passwordResetExpiry?: T;
  passwordChangedAt?: T;
  firstName?: T;
  lastName?: T;
  phoneNumber?: T;
  address?: T;
  references?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-details_select".
 */
export interface BusinessDetailsSelect<T extends boolean = true> {
  companyEmail?: T;
  password?: T;
  companyName?: T;
  companyAddress?: T;
  contact?: T;
  industry?: T;
  emailVerified?: T;
  verificationCode?: T;
  registrationStatus?: T;
  registrationDate?: T;
  lastLogin?: T;
  lastLogout?: T;
  passwordResetToken?: T;
  passwordResetExpiry?: T;
  passwordChangedAt?: T;
  verificationCodeExpiry?: T;
  profilePicture?: T;
  profilePictureUpdatedAt?: T;
  profilePictureId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-campaigns_select".
 */
export interface AdCampaignsSelect<T extends boolean = true> {
  businessId?: T;
  campaignName?: T;
  campaignDescription?: T;
  campaignType?: T;
  budget?: T;
  budgetSpent?: T;
  startDate?: T;
  endDate?: T;
  targetAudience?: T;
  status?: T;
  approvalStatus?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  rejectionReason?: T;
  notes?: T;
  pausedAt?: T;
  pauseReason?: T;
  resumedAt?: T;
  resumeReason?: T;
  cancelledAt?: T;
  cancelReason?: T;
  refundAmount?: T;
  lastStatusChange?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-budgeting_select".
 */
export interface PaymentBudgetingSelect<T extends boolean = true> {
  businessId?: T;
  campaignId?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  customerEmail?: T;
  customerName?: T;
  description?: T;
  paymentReference?: T;
  paystackReference?: T;
  status?: T;
  paidAt?: T;
  paystackResponse?: T;
  selectedPlan?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-plans_select".
 */
export interface SubscriptionPlansSelect<T extends boolean = true> {
  planName?: T;
  planType?: T;
  price?: T;
  currency?: T;
  billingCycle?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-documents_select".
 */
export interface UserDocumentsSelect<T extends boolean = true> {
  userId?: T;
  documentType?: T;
  documentFile?: T;
  verificationStatus?: T;
  rejectionReason?: T;
  uploadedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-bank-details_select".
 */
export interface UserBankDetailsSelect<T extends boolean = true> {
  userId?: T;
  bankName?: T;
  accountName?: T;
  accountNumber?: T;
  verificationStatus?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-training_select".
 */
export interface UserTrainingSelect<T extends boolean = true> {
  userId?: T;
  trainingVideos?:
    | T
    | {
        videoId?: T;
        videoTitle?: T;
        completed?: T;
        completedAt?: T;
        watchTime?: T;
        id?: T;
      };
  termsAccepted?: T;
  termsAcceptedAt?: T;
  trainingCompleted?: T;
  trainingCompletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-onboarding_select".
 */
export interface UserOnboardingSelect<T extends boolean = true> {
  userId?: T;
  currentStep?: T;
  stepsCompleted?:
    | T
    | {
        step?: T;
        completedAt?: T;
        id?: T;
      };
  onboardingStatus?: T;
  startedAt?: T;
  completedAt?: T;
  approvedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-earnings_select".
 */
export interface DriverEarningsSelect<T extends boolean = true> {
  driver?: T;
  scans?: T;
  points?: T;
  amount?: T;
  currency?: T;
  type?: T;
  status?: T;
  description?: T;
  tripId?: T;
  paidAt?: T;
  paymentMethod?: T;
  transactionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-withdrawals_select".
 */
export interface DriverWithdrawalsSelect<T extends boolean = true> {
  driver?: T;
  amount?: T;
  currency?: T;
  status?: T;
  bankDetails?:
    | T
    | {
        bankName?: T;
        accountName?: T;
        accountNumber?: T;
      };
  reason?: T;
  adminNotes?: T;
  processedAt?: T;
  processedBy?: T;
  transactionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-ratings_select".
 */
export interface DriverRatingsSelect<T extends boolean = true> {
  driver?: T;
  rater?: T;
  rating?: T;
  review?: T;
  tripId?: T;
  category?: T;
  isVerified?: T;
  isPublic?: T;
  response?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-notifications_select".
 */
export interface DriverNotificationsSelect<T extends boolean = true> {
  driver?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  actionUrl?: T;
  priority?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-magazines_select".
 */
export interface DriverMagazinesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  imageUrl?: T;
  readTime?: T;
  category?: T;
  isPublished?: T;
  publishedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "driver-magazine-reads_select".
 */
export interface DriverMagazineReadsSelect<T extends boolean = true> {
  driver?: T;
  magazine?: T;
  isRead?: T;
  readAt?: T;
  readProgress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-performance_select".
 */
export interface CampaignPerformanceSelect<T extends boolean = true> {
  campaignId?: T;
  businessId?: T;
  date?: T;
  impressions?: T;
  clicks?: T;
  conversions?: T;
  spend?: T;
  engagementRate?: T;
  clickThroughRate?: T;
  conversionRate?: T;
  costPerClick?: T;
  costPerConversion?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaign-media_select".
 */
export interface CampaignMediaSelect<T extends boolean = true> {
  campaignId?: T;
  businessId?: T;
  fileName?: T;
  fileType?: T;
  fileUrl?: T;
  fileSize?: T;
  description?: T;
  uploadStatus?: T;
  isApproved?: T;
  approvedBy?: T;
  approvedAt?: T;
  rejectionReason?: T;
  uploadedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  businessId?: T;
  campaignId?: T;
  stripePaymentIntentId?: T;
  stripeSessionId?: T;
  amount?: T;
  currency?: T;
  status?: T;
  paymentStatus?: T;
  dueDate?: T;
  paidAt?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        total?: T;
        id?: T;
      };
  subtotal?: T;
  taxRate?: T;
  taxAmount?: T;
  totalAmount?: T;
  notes?: T;
  paymentMethod?: T;
  refundReason?: T;
  refundedAt?: T;
  refundAmount?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-data_select".
 */
export interface AnalyticsDataSelect<T extends boolean = true> {
  campaignId?: T;
  businessId?: T;
  date?: T;
  impressions?: T;
  clicks?: T;
  conversions?: T;
  spend?: T;
  engagementRate?: T;
  clickThroughRate?: T;
  conversionRate?: T;
  costPerClick?: T;
  costPerConversion?: T;
  costPerMille?: T;
  currency?: T;
  source?: T;
  deviceType?: T;
  location?: T;
  ageGroup?: T;
  gender?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-pictures_select".
 */
export interface ProfilePicturesSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  ownerType?: T;
  ownerId?: T;
  isActive?: T;
  uploadedBy?: T;
  fileSize?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}